# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestContact():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_contact(self):
    self.driver.get("http://localhost:8082/")
    self.driver.set_window_size(1382, 744)
    self.driver.find_element(By.LINK_TEXT, "Contact Us").click()
    self.driver.find_element(By.ID, "Name").click()
    self.driver.find_element(By.ID, "Name").send_keys("Thanu")
    self.driver.find_element(By.ID, "Contact_email").click()
    self.driver.find_element(By.ID, "Contact_email").send_keys("thanu@gmail.com")
    self.driver.find_element(By.ID, "Message").click()
    self.driver.find_element(By.ID, "Message").send_keys("Notable to view recipes ")
    self.driver.find_element(By.CSS_SELECTOR, "input:nth-child(7)").click()
  
