# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestViewrecipe():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_viewrecipe(self):
    self.driver.get("http://localhost:8082/")
    self.driver.set_window_size(1382, 744)
    self.driver.find_element(By.LINK_TEXT, "Recipes").click()
    self.driver.find_element(By.NAME, "search_term").click()
    self.driver.find_element(By.NAME, "search_term").send_keys("Vegetable Pulao")
    self.driver.find_element(By.CSS_SELECTOR, ".search-btn").click()
  
