services:
  web:
    build: .
    command: sh -c "python app.py"
    ports:
      - "8082:5000"
    depends_on:
      db:
        condition: service_started
  db:
    image: postgres
    container_name: locall_pgdb
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Thanu_2003
    volumes:
      - local_pgdata:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_containerr
    restart: always
    ports:
      - "8887:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: thanuravi0023@gmail.com
      PGADMIN_DEFAULT_PASSWORD: Thanu-2300
    volumes:
      - pgadmin-data:/var/lib/pgadmin

volumes:
  local_pgdata:
  pgadmin-data: