version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - POSTGRES_DB=Foodie-biss
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Thanu_2003
      - POSTGRES_HOST=db
    networks:
      - appnet

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "8887:80"  # Adjusted port mapping to match your existing setup
    environment:
      PGADMIN_DEFAULT_EMAIL: thanuravi0023@gmail.com
      PGADMIN_DEFAULT_PASSWORD: Thanu_2300
      PGADMIN_LISTEN_PORT: 80
      PGADMIN_SERVER_HOST: db  # Use the service name of your existing PostgreSQL container
      PGADMIN_SERVER_PORT: 5432  # PostgreSQL port
    networks:
      - appnet

networks:
  appnet:
    external: true
